name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Commit built files
        uses: actions/commit@v1
        with:
          author_name: "lovezsh"
          author_email: "shuxhan@163.com"
          message: "Build and deploy"
          files: dist/*
      - name: Push changes
        uses: lovezsh/reaction-speed@main
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
